# Generated by Django 5.2.5 on 2025-08-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
    ]
