# Generated by Django 5.2.5 on 2025-08-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_products',
            field=models.ManyToManyField(related_name='liked_by', to='store.product'),
        ),
    ]
