# Generated by Django 5.2.5 on 2025-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_liked_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='store.product'),
        ),
    ]
