"""
Django settings for my_site project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', default='secret_key') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG',default=True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'portfolio',
    'drf_spectacular',
    'reviews',
    'rest_framework',
    'widget_tweaks',
    'django_filters',
    'store',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'my_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.main_categories_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'my_site.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', default='base_name'),
        'USER': os.getenv('DB_USER', default='base_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', default='base_password'),
        'HOST': os.getenv('DB_HOST', default='base_host'),
        'PORT': os.getenv('DB_PORT', default='base_port'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = (
    ('en', 'English'),
)

LANGUAGE_CODE = 'en'
USE_I18N = True

# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_ROOT = "uploads/"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ALLAUTH
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_URL = '/store/accounts/login/'               
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
LOGIN_REDIRECT_URL = '/store'
ACCOUNT_LOGIN_REDIRECT_URL = None
ACCOUNT_LOGOUT_REDIRECT_URL = '/store'        
ACCOUNT_SESSION_REMEMBER = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',  
        'rest_framework.throttling.AnonRateThrottle', 
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '15/min', 
        'anon': '10/min',
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Reviews App API",
    "DESCRIPTION": """Reviews API Documentation\nBefore using the API for any mutations, please complete the following steps:\n1. Register an account on the Django NoAPI Store website:`/store/accounts/signup/` \n\n 2. Obtain a JWT access token by making a POST request to `/api/token/` (login) or refresh it via `/api/token/refresh/`.\n3. Use the access token to authorize your requests in Swagger by clicking the "Authorize" button and entering:\n`Bearer <your_access_token>`""",
    "VERSION": "1.0.0",
    "TAGS": [
        {"name": "Authentication","description": "Endpoints for user authentication, including obtaining and refreshing jwt access tokens."},
        {"name": "Product","description": "Endpoints for managing products."},
        {"name": "Review","description": "Endpoints for handling product reviews."},
        {"name": "Comment","description": "Endpoints for managing comments on reviews."}
    ],
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    "SECURITY": [{"bearerAuth": []}],
}

SPECTACULAR_SETTINGS['SECURITY_SCHEMES'] = {
    'bearerAuth': {
        'type': 'http',
        'scheme': 'bearer',
        'bearerFormat': 'JWT',
    }
}
